### ISSUE TITLE
Error rendering in latest framework

### ISSUE THREAD

**Issue by joe-replin** [cgkineo/adapt-list#32]
In v5.15.2, I'm receiving the following error which is preventing my page from loading.
adapt.min.js:28168:1
Uncaught (in promise) TypeError: _items is undefined

Removing the list component fixes the issue.

Tested in Window 10 Firefox 90.0.2

**Comment by oliverfoster** [comment]
You always need to post errors with unminified sourcecode / with sourcemaps enabled.
adapt.min.js:28168:1 Is a reference to a position in a minified file which doesn't give the line of error.

It could be here https://github.com/cgkineo/adapt-list/blob/669f1ab02b300c6a4ba6610e7ead55319bc1f878/templates/list.jsx#L20

In which case it needs `_items && _items.map`

**Comment by joe-replin** [comment]
Hello, the latest changes are good on my end. Thank you!
