### ISSUE TITLE
List component headings do not have aria-labels or role attribute 

### ISSUE THREAD

**Issue by StuartNicholls** [cgkineo/adapt-list#36]
List headings do not have aria-labels or role attribute when the title attribute in the JSOn is set.

**Comment by kirsty-hames** [comment]
Agreed, we should be using `a11y_attrs_heading` for consistency with [other component item titles](https://github.com/adaptlearning/adapt-contrib-narrative/blob/9e5e886fc8da48f36bbf79476c9580cda45d6ab0/templates/narrative.hbs#L15).
