### ISSUE TITLE
Auto levels calculating incorrect value

### ISSUE THREAD

**Issue by StuartNicholls** [cgkineo/adapt-list#38]
Increments from _ariaLevel if it exists. AriaLevel is 0 (zero) by default, which will then report the heading level incorrectly/ 

Affects corses from exported from the authoring tool.

Suggest updating check for 0

**Comment by kirsty-hames** [comment]
Is _ariaLevel still needed now that we have automated aria levels @StuartNicholls @oliverfoster. I'm asking this as a global query, not just specific to List. I can't see we would need to manually override now?

**Comment by oliverfoster** [comment]
@kirsty-hames could you raise the removal of _ariaLevel in core please

**Comment by kirsty-hames** [comment]
> @kirsty-hames could you raise the removal of _ariaLevel in core please, and then close this issue

Issue raised https://github.com/adaptlearning/adapt-contrib-core/issues/442
