### ISSUE TITLE
Lorem ipsum in example.json

### ISSUE THREAD

**Issue by tomallpress** [cgkineo/adapt-list#6]
Minor issue but can we replace the meat variant of lorem ipsum with the standard variation please? logging here just so i remember, and i'll try and sort out a pull request when i've got a sec

**Comment by moloko** [comment]
boo-ring! but yeah fair enough ;-) if you want to just send me a new example.json I'll happily commit it for you, no need to go through the PR process

**Comment by tomallpress** [comment]
yeeeeeeeah, i knowwwwww. ah great perfect, will do. thanks!
