### ISSUE TITLE
Can't upload plugin to v1 AAT

### ISSUE THREAD

**Issue by kineopete** [cgkineo/adapt-list#72]
### Subject of the issue/enhancement/features
Plugin upload triggers the following error:
![image](https://github.com/cgkineo/adapt-list/assets/9944984/eda6be28-14ea-4b5c-99ba-516a5427e433)

### Your environment
* version 1.0.0-rc.3, 5.24.8

**Comment by swashbuck** [comment]
I just updated List to 5.3.2 on Staging, and it seems to be working fine.

- Framework 5.31.16
- AAT 1.0.0-rc.3
- List 5.3.2

Closing this ticket.
