### ISSUE TITLE
Optimise RTL styling

### ISSUE THREAD

**Issue by guywillis** [cgkineo/adapt-list#78]
### Subject of the enhancement
The RTL styling present in the `list.less` file could be optimised a touch better by utilising the [padding-inline-end](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-end) property instead of the current approach.

The `padding-inline-end` property does not require an associated RTL version as the property inherits the body direction.

Current approach:

```
&__image-container {
  padding-right: @item-padding;

  .dir-rtl & {
    padding-right: inherit;
    padding-left: @item-padding;
  }
}
```

Proposed solution:

```
&__image-container {
  padding-inline-end: @item-padding;
}
```

### Your environment
* Master

**Comment by oliverfoster** [comment]
Not ie compatible.
